# Generated by Django 5.2.6 on 2025-09-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200316_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('MovieID', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(max_length=100)),
                ('Actor2Name', models.CharField(blank=True, max_length=100, null=True)),
                ('DirectorName', models.CharField(max_length=100)),
                ('MovieGenre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Other', 'Other')], default='Other', max_length=50)),
                ('ReleaseYear', models.PositiveIntegerField()),
                ('DurationMinutes', models.PositiveIntegerField(default=90)),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Taken',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
